# Dataset Preparation

In [1]:
import pandas as pd

## human-AI-generatedTextCorpus

In [2]:
# wiki or news
domain = "wiki"

human_features_df =  pd.read_pickle("../raw_data/en_wiki_human_features_df.pkl")
gpt_features_df =  pd.read_pickle("../raw_data/en_wiki_gpt_features_df.pkl")

In [3]:
human_features_df["Label"] = "Human"
human_features_df.rename(columns={"text":"Text"}, inplace=True)
human_features_df = human_features_df[["Label", "Text"]]
human_features_df.head()

     Label                                               Text
336  Human  Chemistry is the scientific study of the prope...
214  Human  Buddhism, also known as Buddha Dharma or Dharm...
282  Human  Color or colour is the visual perceptual prope...
182  Human  In the fields of molecular biology and genetic...
178  Human  Photosynthesis is a process used by plants and...

In [4]:
gpt_features_df["Label"] = "OpenAI"
gpt_features_df.rename(columns={"text":"Text"}, inplace=True)
gpt_features_df = gpt_features_df[["Label", "Text"]]
gpt_features_df.head()

     Label                                               Text
12  OpenAI  Vienna, the capital and largest city of Austri...
13  OpenAI  Vienna, located in Austria, is the country's c...
14  OpenAI  Vienna, the capital of Austria, is a city rich...
15  OpenAI  Vienna is a beautiful and historic city locate...
20  OpenAI  The Himalayas, also known as Himalaya, form a ...

In [5]:
df_1 = pd.concat([human_features_df, gpt_features_df])
df_1["word_count"] = df_1.apply(lambda row: len(row["Text"].split()), axis=1)
df_1.reset_index(drop=True, inplace=True)
df_1

      Label                                               Text  word_count
0     Human  Chemistry is the scientific study of the prope...         211
1     Human  Buddhism, also known as Buddha Dharma or Dharm...         347
2     Human  Color or colour is the visual perceptual prope...         164
3     Human  In the fields of molecular biology and genetic...         171
4     Human  Photosynthesis is a process used by plants and...         476
..      ...                                                ...         ...
495  OpenAI  The Constitution is a document that provides t...         249
496  OpenAI  The symbol χ represents electronegativity, whi...         170
497  OpenAI  Electronegativity is a property of atoms that ...         158
498  OpenAI  Electronegativity is a fundamental concept in ...         289
499  OpenAI  Electronegativity is a fundamental concept in ...         254

[500 rows x 3 columns]

## GPT vs. Human: A Corpus of Research Abstracts

In [6]:
df = pd.read_csv('../raw_data/gptvshuman_dataset.csv')
df

,title,abstract,ai_generated,is_ai_generated
0,Are Advanced Potentials Anomalous?,Advanced electromagnetic potentials are indi...,False,0
1,Are Advanced Potentials Anomalous?,This research paper investigates the question ...,True,1
2,An efficient centralized binary multicast netw...,We give an algorithm for finding network enc...,False,0
3,An efficient centralized binary multicast netw...,The paper presents an efficient centralized bi...,True,1
4,Percolation transition in networks with degree...,We introduce an exponential random graph mod...,False,0
...,...,...,...,...
4048,Vortex Dynamics at the Initial Stage of Resist...,This research paper investigates the vortex dy...,True,1
4049,The Veldkamp Space of Two-Qubits,Given a remarkable representation of the gen...,False,0
4050,The Veldkamp Space of Two-Qubits,The Veldkamp space of two-qubits is a mathemat...,True,1
4051,Fusion process studied with preequilibrium gia...,The equilibration of macroscopic degrees of ...,False,0
4052,Fusion process studied with preequilibrium gia...,This research paper investigates the fusion pr...,True,1

In [7]:
df["Label"] = df.apply(lambda row: "OpenAI" if row["ai_generated"] else "Human", axis = 1)
df

,title,abstract,ai_generated,is_ai_generated,Label
0,Are Advanced Potentials Anomalous?,Advanced electromagnetic potentials are indi...,False,0,Human
1,Are Advanced Potentials Anomalous?,This research paper investigates the question ...,True,1,OpenAI
2,An efficient centralized binary multicast netw...,We give an algorithm for finding network enc...,False,0,Human
3,An efficient centralized binary multicast netw...,The paper presents an efficient centralized bi...,True,1,OpenAI
4,Percolation transition in networks with degree...,We introduce an exponential random graph mod...,False,0,Human
...,...,...,...,...,...
4048,Vortex Dynamics at the Initial Stage of Resist...,This research paper investigates the vortex dy...,True,1,OpenAI
4049,The Veldkamp Space of Two-Qubits,Given a remarkable representation of the gen...,False,0,Human
4050,The Veldkamp Space of Two-Qubits,The Veldkamp space of two-qubits is a mathemat...,True,1,OpenAI
4051,Fusion process studied with preequilibrium gia...,The equilibration of macroscopic degrees of ...,False,0,Human
4052,Fusion process studied with preequilibrium gia...,This research paper investigates the fusion pr...,True,1,OpenAI

In [8]:
df.rename(columns={"abstract":"Text"}, inplace=True)
df

,title,Text,ai_generated,is_ai_generated,Label
0,Are Advanced Potentials Anomalous?,Advanced electromagnetic potentials are indi...,False,0,Human
1,Are Advanced Potentials Anomalous?,This research paper investigates the question ...,True,1,OpenAI
2,An efficient centralized binary multicast netw...,We give an algorithm for finding network enc...,False,0,Human
3,An efficient centralized binary multicast netw...,The paper presents an efficient centralized bi...,True,1,OpenAI
4,Percolation transition in networks with degree...,We introduce an exponential random graph mod...,False,0,Human
...,...,...,...,...,...
4048,Vortex Dynamics at the Initial Stage of Resist...,This research paper investigates the vortex dy...,True,1,OpenAI
4049,The Veldkamp Space of Two-Qubits,Given a remarkable representation of the gen...,False,0,Human
4050,The Veldkamp Space of Two-Qubits,The Veldkamp space of two-qubits is a mathemat...,True,1,OpenAI
4051,Fusion process studied with preequilibrium gia...,The equilibration of macroscopic degrees of ...,False,0,Human
4052,Fusion process studied with preequilibrium gia...,This research paper investigates the fusion pr...,True,1,OpenAI

In [9]:
df_2 = df[["Label", "Text"]]
df_2["word_count"] = df_2.apply(lambda row: len(row["Text"].split()), axis=1)
df_2.reset_index(drop=True, inplace=True)
df_2

C:\Users\cinthia.nagahama.VERT\AppData\Local\Temp\ipykernel_7316\1785139674.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2["word_count"] = df_2.apply(lambda row: len(row["Text"].split()), axis=1)

       Label                                               Text  word_count
0      Human    Advanced electromagnetic potentials are indi...         164
1     OpenAI  This research paper investigates the question ...          93
2      Human    We give an algorithm for finding network enc...          77
3     OpenAI  The paper presents an efficient centralized bi...         125
4      Human    We introduce an exponential random graph mod...         139
...      ...                                                ...         ...
4048  OpenAI  This research paper investigates the vortex dy...          90
4049   Human    Given a remarkable representation of the gen...          91
4050  OpenAI  The Veldkamp space of two-qubits is a mathemat...         130
4051   Human    The equilibration of macroscopic degrees of ...         163
4052  OpenAI  This research paper investigates the fusion pr...          92

[4053 rows x 3 columns]

## AI vs Human Scientific Text Dataset (AIGTxt)

In [10]:
df = pd.read_csv('../raw_data/AIGTxt.csv', delimiter=";")
df

,Human-Generated,ChatGPT-Generated,Mixed Text,Domain,Unnamed: 4
0,Photo-realistic image rendering using standard...,Achieving photo-realistic image rendering thro...,Achieving photo-realistic image rendering thro...,Computer Science and Artificial Intelligence,NaN
1,The Large Hadron Collider is exploring physics...,The Large Hadron Collider (LHC) serves as a fr...,The Large Hadron Collider (LHC) serves as a fr...,Computer Science and Artificial Intelligence,NaN
2,With the rapid development of mobile Internet ...,In the era of swift advancements in mobile Int...,In the era of swift advancements in mobile Int...,Computer Science and Artificial Intelligence,NaN
3,Most contour tracking methods can be grouped i...,Contour tracking methods can be broadly catego...,Contour tracking methods can be broadly catego...,Computer Science and Artificial Intelligence,NaN
4,Year 2010 is regarded as the breakthrough year...,The pivotal year 2010 marked a significant bre...,The pivotal year 2010 marked a significant bre...,Computer Science and Artificial Intelligence,NaN
...,...,...,...,...,...
3602,The increasing infrastructure instability is a...,Urban areas are increasingly experiencing infr...,Urban areas are increasingly experiencing infr...,Social Sciences and Humanities,NaN
3603,Even though it is commonly understood that mor...,While it is widely acknowledged that addressin...,While it is widely acknowledged that addressin...,Social Sciences and Humanities,NaN
3604,With the realisation that stakeholders across ...,Educational practitioners and academics have i...,With the realisation that stakeholders across ...,Social Sciences and Humanities,NaN
3605,"In this room, created by the non-governmental ...","Within this space, established by the non-gove...","Within this space, established by the non-gove...",Social Sciences and Humanities,NaN
3606,"Young onset dementias (YOD), i.e. dementias pr...","Young onset dementias (YOD), referring to deme...","Young onset dementias (YOD), referring to deme...",Social Sciences and Humanities,NaN

In [11]:
df_human = pd.DataFrame(df["Human-Generated"])
df_human.rename(columns={"Human-Generated":"Text"}, inplace=True)
df_human["Label"] = "Human"
df_human

                                                   Text  Label
0     Photo-realistic image rendering using standard...  Human
1     The Large Hadron Collider is exploring physics...  Human
2     With the rapid development of mobile Internet ...  Human
3     Most contour tracking methods can be grouped i...  Human
4     Year 2010 is regarded as the breakthrough year...  Human
...                                                 ...    ...
3602  The increasing infrastructure instability is a...  Human
3603  Even though it is commonly understood that mor...  Human
3604  With the realisation that stakeholders across ...  Human
3605  In this room, created by the non-governmental ...  Human
3606  Young onset dementias (YOD), i.e. dementias pr...  Human

[3607 rows x 2 columns]

In [12]:
df_ai = pd.DataFrame(df["ChatGPT-Generated"])
df_ai.rename(columns={"ChatGPT-Generated":"Text"}, inplace=True)
df_ai["Label"] = "OpenAI"
df_ai

                                                   Text   Label
0     Achieving photo-realistic image rendering thro...  OpenAI
1     The Large Hadron Collider (LHC) serves as a fr...  OpenAI
2     In the era of swift advancements in mobile Int...  OpenAI
3     Contour tracking methods can be broadly catego...  OpenAI
4     The pivotal year 2010 marked a significant bre...  OpenAI
...                                                 ...     ...
3602  Urban areas are increasingly experiencing infr...  OpenAI
3603  While it is widely acknowledged that addressin...  OpenAI
3604  Educational practitioners and academics have i...  OpenAI
3605  Within this space, established by the non-gove...  OpenAI
3606  Young onset dementias (YOD), referring to deme...  OpenAI

[3607 rows x 2 columns]

In [13]:
df_3 = pd.concat([df_human, df_ai])
df_3["word_count"] = df_3.apply(lambda row: len(row["Text"].split()), axis=1)
df_3.reset_index(drop=True, inplace=True)
df_3

                                                   Text   Label  word_count
0     Photo-realistic image rendering using standard...   Human         121
1     The Large Hadron Collider is exploring physics...   Human         133
2     With the rapid development of mobile Internet ...   Human         153
3     Most contour tracking methods can be grouped i...   Human         189
4     Year 2010 is regarded as the breakthrough year...   Human         213
...                                                 ...     ...         ...
7209  Urban areas are increasingly experiencing infr...  OpenAI         140
7210  While it is widely acknowledged that addressin...  OpenAI         184
7211  Educational practitioners and academics have i...  OpenAI         193
7212  Within this space, established by the non-gove...  OpenAI         208
7213  Young onset dementias (YOD), referring to deme...  OpenAI         231

[7214 rows x 3 columns]

## Human vs. LLM Text Corpus

In [14]:
df = pd.read_csv('../raw_data/humanvsllm_data.csv')
df

,text,source,prompt_id,text_length,word_count
0,"Federal law supersedes state law, and cannabis...",Bloom-7B,0,967,157
1,Miles feels restless after working all day. He...,Bloom-7B,0,5068,778
2,So first of I am danish. That means that I fol...,Bloom-7B,0,1602,267
3,In this paper we present a novel rule-based ap...,Bloom-7B,0,5469,848
4,"Most social progressives, love democracy, and ...",Bloom-7B,0,2379,380
...,...,...,...,...,...
788917,"\nIn the vast expanse of time, where the echoe...",YI-34B,1293,5523,870
788918,"\nThe phenomenon of brain drain, particularly ...",YI-34B,1154,4540,677
788919,\nThe Influence of Climate Change on Marine Ec...,YI-34B,2783,3889,598
788920,\nTitle: The Case for Limiting Car Usage: Navi...,YI-34B,41,3560,533
788921,"\nIn the vast expanse of a globalized society,...",YI-34B,4318,4563,693

In [15]:
source_mapping = {
    "Human": "Human",
    "GPT-3.5": "OpenAI",
    "Text-Davinci-003": "OpenAI",
    "Text-Davinci-002": "OpenAI",
    "OPT-1.3B": "Meta",
    "OPT-30B": "Meta",
    "PaLM-2": "Google",
    "LLaMA-30B": "Meta",
    "LLaMA-65B": "Meta",
    "LLaMA-13B": "Meta",
    "LLaMA-7B": "Meta",
    "Flan-T5-Base": "Google",
    "Flan-T5-Large": "Google",
    "Flan-T5-Small": "Google",
    "OPT-2.7B": "Meta",
    "Flan-T5-XXL": "Google",
    "Flan-T5-XL": "Google",
    "GPT-4": "OpenAI",
    "OPT-6.7B": "Meta",
    "OPT-125M": "Meta",
    "OPT-350M": "Meta",
    "OPT-13B": "Meta",
    "GPT-J": "OpenAI",
    "Claude-Instant-v1": "Anthropic",
    "GPT-NeoX": "OpenAI",
    "LLaMA-2-70B": "Meta",
    "Claude-v1": "Anthropic",
    "Gemini-Pro": "Google",
    "LLaMA-2-7B": "Meta"
}

In [16]:
df = df[df["source"].isin(source_mapping.keys())][["source", "text", "word_count"]]
df.rename(columns={"source":"Label"}, inplace=True)
df

,Label,text,word_count
8812,Claude-Instant-v1,The rapid disappearance of forests around the...,585
8813,Claude-Instant-v1,The Healing Garden\n\nIt was a warm summer ev...,444
8814,Claude-Instant-v1,Drivers Should Avoid Cell Phone Use While Oper...,323
8815,Claude-Instant-v1,I agree with the principal's decision that all...,277
8816,Claude-Instant-v1,"Dear Principal Johnson, \n\nI am writing to ex...",368
...,...,...,...
778871,Text-Davinci-003,"The first amendment has the ""Free Exercise"" cl...",77
778872,Text-Davinci-003,It means a plasma that is made of quarks and g...,85
778873,Text-Davinci-003,ISIS has been successful at recruiting middle ...,143
778874,Text-Davinci-003,A researcher from the Swiss research institute...,227
778875,Text-Davinci-003,It is not true that Islam is incompatible with...,114

In [17]:
df["Text"] = df["text"].str.replace(r"[\n\r]", " ", regex=True)

In [18]:
df.head()

,Label,text,word_count,Text
8812,Claude-Instant-v1,The rapid disappearance of forests around the...,585,The rapid disappearance of forests around the...
8813,Claude-Instant-v1,The Healing Garden\n\nIt was a warm summer ev...,444,The Healing Garden It was a warm summer even...
8814,Claude-Instant-v1,Drivers Should Avoid Cell Phone Use While Oper...,323,Drivers Should Avoid Cell Phone Use While Oper...
8815,Claude-Instant-v1,I agree with the principal's decision that all...,277,I agree with the principal's decision that all...
8816,Claude-Instant-v1,"Dear Principal Johnson, \n\nI am writing to ex...",368,"Dear Principal Johnson, I am writing to expr..."

In [19]:
df_4 = pd.DataFrame(df[["Text", "word_count"]])
df_4["Label"] = df.apply(lambda row: source_mapping[row["Label"]], axis=1)
df_4.reset_index(drop=True, inplace=True)
df_4

,Text,word_count,Label
0,The rapid disappearance of forests around the...,585,Anthropic
1,The Healing Garden It was a warm summer even...,444,Anthropic
2,Drivers Should Avoid Cell Phone Use While Oper...,323,Anthropic
3,I agree with the principal's decision that all...,277,Anthropic
4,"Dear Principal Johnson, I am writing to expr...",368,Anthropic
...,...,...,...
656392,"The first amendment has the ""Free Exercise"" cl...",77,OpenAI
656393,It means a plasma that is made of quarks and g...,85,OpenAI
656394,ISIS has been successful at recruiting middle ...,143,OpenAI
656395,A researcher from the Swiss research institute...,227,OpenAI
656396,It is not true that Islam is incompatible with...,114,OpenAI

## Final Dataset

In [20]:
df_final = pd.concat([df_1, df_2, df_3, df_4])
df_final.shape

(668164, 3)

In [21]:
df_final["basic_text"] = df_final["Text"].str.upper()
df_final.head()

,Label,Text,word_count,basic_text
0,Human,Chemistry is the scientific study of the prope...,211,CHEMISTRY IS THE SCIENTIFIC STUDY OF THE PROPE...
1,Human,"Buddhism, also known as Buddha Dharma or Dharm...",347,"BUDDHISM, ALSO KNOWN AS BUDDHA DHARMA OR DHARM..."
2,Human,Color or colour is the visual perceptual prope...,164,COLOR OR COLOUR IS THE VISUAL PERCEPTUAL PROPE...
3,Human,In the fields of molecular biology and genetic...,171,IN THE FIELDS OF MOLECULAR BIOLOGY AND GENETIC...
4,Human,Photosynthesis is a process used by plants and...,476,PHOTOSYNTHESIS IS A PROCESS USED BY PLANTS AND...

In [22]:
df_final = df_final.drop_duplicates(subset=['basic_text'])
df_final.drop("basic_text", axis=1, inplace=True)
df_final.shape

(668096, 3)

In [23]:
df_short = df_final[df_final["word_count"] <= 120]
df_short.reset_index(drop=True, inplace=True)
df_short.Label.value_counts(dropna=False)

Label
Human     70610
Google    43638
OpenAI    40497
Meta      39907
Name: count, dtype: int64

In [27]:
df_tmp = df_final[df_final["Label"] == "Anthropic"]
df_final_mini = df_short[df_short["Label"] != "Human"].groupby("Label").sample(n=30000, random_state=42)
df_final_mini = pd.concat([df_final_mini, df_tmp, df_short[df_short["Label"] == "Human"]])
df_final_mini.Label.value_counts(dropna=False)

Label
Human        70610
Google       30000
Meta         30000
OpenAI       30000
Anthropic    10305
Name: count, dtype: int64

In [28]:
df_final_mini.to_csv('../custom_dataset_v2_mini.csv', sep=";", index_label="ID")