# Dataset Preparation

In [1]:
import pandas as pd

## human-AI-generatedTextCorpus

In [3]:
# wiki or news
domain = "wiki"

human_features_df =  pd.read_pickle("../raw_data/en_wiki_human_features_df.pkl")
gpt_features_df =  pd.read_pickle("../raw_data/en_wiki_gpt_features_df.pkl")

In [4]:
human_features_df["source"] = "human"
human_features_df = human_features_df[["source", "text"]]

In [5]:
human_features_df.head()

    source                                               text
336  human  Chemistry is the scientific study of the prope...
214  human  Buddhism, also known as Buddha Dharma or Dharm...
282  human  Color or colour is the visual perceptual prope...
182  human  In the fields of molecular biology and genetic...
178  human  Photosynthesis is a process used by plants and...

In [6]:
gpt_features_df["source"] = "openai"
gpt_features_df = gpt_features_df[["source", "text"]]

In [7]:
gpt_features_df.head()

    source                                               text
12  openai  Vienna, the capital and largest city of Austri...
13  openai  Vienna, located in Austria, is the country's c...
14  openai  Vienna, the capital of Austria, is a city rich...
15  openai  Vienna is a beautiful and historic city locate...
20  openai  The Himalayas, also known as Himalaya, form a ...

In [8]:
df_1 = pd.concat([human_features_df, gpt_features_df])
df_1.reset_index(drop=True, inplace=True)
df_1

     source                                               text
0     human  Chemistry is the scientific study of the prope...
1     human  Buddhism, also known as Buddha Dharma or Dharm...
2     human  Color or colour is the visual perceptual prope...
3     human  In the fields of molecular biology and genetic...
4     human  Photosynthesis is a process used by plants and...
..      ...                                                ...
495  openai  The Constitution is a document that provides t...
496  openai  The symbol χ represents electronegativity, whi...
497  openai  Electronegativity is a property of atoms that ...
498  openai  Electronegativity is a fundamental concept in ...
499  openai  Electronegativity is a fundamental concept in ...

[500 rows x 2 columns]

## GPT vs. Human: A Corpus of Research Abstracts

In [9]:
df = pd.read_csv('../raw_data/gptvshuman_dataset.csv')
df

,title,abstract,ai_generated,is_ai_generated
0,Are Advanced Potentials Anomalous?,Advanced electromagnetic potentials are indi...,False,0
1,Are Advanced Potentials Anomalous?,This research paper investigates the question ...,True,1
2,An efficient centralized binary multicast netw...,We give an algorithm for finding network enc...,False,0
3,An efficient centralized binary multicast netw...,The paper presents an efficient centralized bi...,True,1
4,Percolation transition in networks with degree...,We introduce an exponential random graph mod...,False,0
...,...,...,...,...
4048,Vortex Dynamics at the Initial Stage of Resist...,This research paper investigates the vortex dy...,True,1
4049,The Veldkamp Space of Two-Qubits,Given a remarkable representation of the gen...,False,0
4050,The Veldkamp Space of Two-Qubits,The Veldkamp space of two-qubits is a mathemat...,True,1
4051,Fusion process studied with preequilibrium gia...,The equilibration of macroscopic degrees of ...,False,0
4052,Fusion process studied with preequilibrium gia...,This research paper investigates the fusion pr...,True,1

In [10]:
df["source"] = df.apply(lambda row: "openai" if row["ai_generated"] else "human", axis = 1)
df

,title,abstract,ai_generated,is_ai_generated,source
0,Are Advanced Potentials Anomalous?,Advanced electromagnetic potentials are indi...,False,0,human
1,Are Advanced Potentials Anomalous?,This research paper investigates the question ...,True,1,openai
2,An efficient centralized binary multicast netw...,We give an algorithm for finding network enc...,False,0,human
3,An efficient centralized binary multicast netw...,The paper presents an efficient centralized bi...,True,1,openai
4,Percolation transition in networks with degree...,We introduce an exponential random graph mod...,False,0,human
...,...,...,...,...,...
4048,Vortex Dynamics at the Initial Stage of Resist...,This research paper investigates the vortex dy...,True,1,openai
4049,The Veldkamp Space of Two-Qubits,Given a remarkable representation of the gen...,False,0,human
4050,The Veldkamp Space of Two-Qubits,The Veldkamp space of two-qubits is a mathemat...,True,1,openai
4051,Fusion process studied with preequilibrium gia...,The equilibration of macroscopic degrees of ...,False,0,human
4052,Fusion process studied with preequilibrium gia...,This research paper investigates the fusion pr...,True,1,openai

In [11]:
df.rename(columns={"abstract":"text"}, inplace=True)
df

,title,text,ai_generated,is_ai_generated,source
0,Are Advanced Potentials Anomalous?,Advanced electromagnetic potentials are indi...,False,0,human
1,Are Advanced Potentials Anomalous?,This research paper investigates the question ...,True,1,openai
2,An efficient centralized binary multicast netw...,We give an algorithm for finding network enc...,False,0,human
3,An efficient centralized binary multicast netw...,The paper presents an efficient centralized bi...,True,1,openai
4,Percolation transition in networks with degree...,We introduce an exponential random graph mod...,False,0,human
...,...,...,...,...,...
4048,Vortex Dynamics at the Initial Stage of Resist...,This research paper investigates the vortex dy...,True,1,openai
4049,The Veldkamp Space of Two-Qubits,Given a remarkable representation of the gen...,False,0,human
4050,The Veldkamp Space of Two-Qubits,The Veldkamp space of two-qubits is a mathemat...,True,1,openai
4051,Fusion process studied with preequilibrium gia...,The equilibration of macroscopic degrees of ...,False,0,human
4052,Fusion process studied with preequilibrium gia...,This research paper investigates the fusion pr...,True,1,openai

In [12]:
df_2 = df[["source", "text"]]
df_2.reset_index(drop=True, inplace=True)
df_2

      source                                               text
0      human    Advanced electromagnetic potentials are indi...
1     openai  This research paper investigates the question ...
2      human    We give an algorithm for finding network enc...
3     openai  The paper presents an efficient centralized bi...
4      human    We introduce an exponential random graph mod...
...      ...                                                ...
4048  openai  This research paper investigates the vortex dy...
4049   human    Given a remarkable representation of the gen...
4050  openai  The Veldkamp space of two-qubits is a mathemat...
4051   human    The equilibration of macroscopic degrees of ...
4052  openai  This research paper investigates the fusion pr...

[4053 rows x 2 columns]

## AI-Generated Text Detection (Multi-Model)

In [13]:
df = pd.read_csv('../raw_data/benchmark_ai_detection_multimodel_2026.csv')
df

,id,timestamp,domain_context,source_model,is_ai_generated,text_content,word_count,readability_score,avg_sentence_length,simulated_perplexity,label_confidence
0,de00499a-a413-4d81-b07d-2ce1c54dd27b,2025-01-06 15:39:56,Medical_Diagnosis_Summary,GPT-5_Preview,1,"Furthermore, Clinical diagnosis clinical respi...",22,-48.702045,4.40,18.15,0.8527
1,6b4603c7-21c3-4290-830a-c9bff4cf6842,2025-01-06 18:56:37,Medical_Diagnosis_Summary,Claude-4_Opus,1,It is imperative to note that Diagnosis diagno...,40,-21.040000,5.00,19.08,0.8602
2,98e69cdf-4b68-4606-874f-b97a8775d5d7,2025-01-08 13:19:23,Legal_Contract_Review,Gemini-2_Pro,1,Based on the available data: Liability termina...,31,-8.544651,4.43,24.83,0.9290
3,0d770e65-4657-42da-b571-b71faf062759,2025-01-08 23:50:36,Legal_Contract_Review,GPT-5_Preview,1,"Furthermore, Termination clause statute statut...",34,-55.204902,4.86,16.99,0.8516
4,10b7bbdd-ed0c-4fd0-b183-c2f2735d2687,2025-01-09 11:48:37,Software_Architecture_Doc,Gemini-2_Pro,1,Based on the available data: Security coach jo...,36,46.777000,6.00,12.38,0.8649
...,...,...,...,...,...,...,...,...,...,...,...
495,a097597b-94e4-47f4-8261-bae28ec83d79,2025-12-30 13:01:25,Medical_Diagnosis_Summary,Gemini-2_Pro,1,Based on the available data: Prognosis symptom...,47,-21.380000,5.88,22.28,0.9467
496,0f66c063-9310-429c-a6ee-f536eaa2605a,2025-12-30 18:13:39,Cybersecurity_Report,Gemini-2_Pro,1,Based on the available data: Protocol malware ...,30,21.562500,6.00,24.70,0.9208
497,244534d1-b786-4e41-abef-7f5bbfb40c76,2025-12-31 21:28:01,Software_Architecture_Doc,Gemini-2_Pro,1,Based on the available data: Cold ever whose. ...,47,40.671875,5.22,18.65,0.9060
498,518fff92-77dd-44d1-94ff-9b1a09d014b4,2026-01-02 06:31:55,Medical_Diagnosis_Summary,Human,0,diagnosis cardiac clinical cardiac clinical pa...,24,-69.462000,4.00,43.96,0.9102
499,ea2d2c2c-8b06-4b9c-b985-caba358084ed,2026-01-04 06:08:14,Medical_Diagnosis_Summary,Claude-4_Opus,1,It is imperative to note that Clinical diagnos...,37,-18.926869,5.29,18.91,0.8824

In [14]:
df["source_model"].value_counts(dropna=False)

source_model
Human            180
Gemini-2_Pro     118
GPT-5_Preview    107
Claude-4_Opus     95
Name: count, dtype: int64

In [15]:
model_mapping = {
    "Human": "human",
    "Gemini-2_Pro": "google",
    "GPT-5_Preview": "openai",
    "Claude-4_Opus": "anthropic"
}

In [16]:
df.rename(columns={"text_content":"text"}, inplace=True)
df["source"] = df.apply(lambda row: model_mapping[row["source_model"]], axis=1)
df

,id,timestamp,domain_context,source_model,is_ai_generated,text,word_count,readability_score,avg_sentence_length,simulated_perplexity,label_confidence,source
0,de00499a-a413-4d81-b07d-2ce1c54dd27b,2025-01-06 15:39:56,Medical_Diagnosis_Summary,GPT-5_Preview,1,"Furthermore, Clinical diagnosis clinical respi...",22,-48.702045,4.40,18.15,0.8527,openai
1,6b4603c7-21c3-4290-830a-c9bff4cf6842,2025-01-06 18:56:37,Medical_Diagnosis_Summary,Claude-4_Opus,1,It is imperative to note that Diagnosis diagno...,40,-21.040000,5.00,19.08,0.8602,anthropic
2,98e69cdf-4b68-4606-874f-b97a8775d5d7,2025-01-08 13:19:23,Legal_Contract_Review,Gemini-2_Pro,1,Based on the available data: Liability termina...,31,-8.544651,4.43,24.83,0.9290,google
3,0d770e65-4657-42da-b571-b71faf062759,2025-01-08 23:50:36,Legal_Contract_Review,GPT-5_Preview,1,"Furthermore, Termination clause statute statut...",34,-55.204902,4.86,16.99,0.8516,openai
4,10b7bbdd-ed0c-4fd0-b183-c2f2735d2687,2025-01-09 11:48:37,Software_Architecture_Doc,Gemini-2_Pro,1,Based on the available data: Security coach jo...,36,46.777000,6.00,12.38,0.8649,google
...,...,...,...,...,...,...,...,...,...,...,...,...
495,a097597b-94e4-47f4-8261-bae28ec83d79,2025-12-30 13:01:25,Medical_Diagnosis_Summary,Gemini-2_Pro,1,Based on the available data: Prognosis symptom...,47,-21.380000,5.88,22.28,0.9467,google
496,0f66c063-9310-429c-a6ee-f536eaa2605a,2025-12-30 18:13:39,Cybersecurity_Report,Gemini-2_Pro,1,Based on the available data: Protocol malware ...,30,21.562500,6.00,24.70,0.9208,google
497,244534d1-b786-4e41-abef-7f5bbfb40c76,2025-12-31 21:28:01,Software_Architecture_Doc,Gemini-2_Pro,1,Based on the available data: Cold ever whose. ...,47,40.671875,5.22,18.65,0.9060,google
498,518fff92-77dd-44d1-94ff-9b1a09d014b4,2026-01-02 06:31:55,Medical_Diagnosis_Summary,Human,0,diagnosis cardiac clinical cardiac clinical pa...,24,-69.462000,4.00,43.96,0.9102,human
499,ea2d2c2c-8b06-4b9c-b985-caba358084ed,2026-01-04 06:08:14,Medical_Diagnosis_Summary,Claude-4_Opus,1,It is imperative to note that Clinical diagnos...,37,-18.926869,5.29,18.91,0.8824,anthropic

In [17]:
df_3 = df[["source", "text"]]
df_3

        source                                               text
0       openai  Furthermore, Clinical diagnosis clinical respi...
1    anthropic  It is imperative to note that Diagnosis diagno...
2       google  Based on the available data: Liability termina...
3       openai  Furthermore, Termination clause statute statut...
4       google  Based on the available data: Security coach jo...
..         ...                                                ...
495     google  Based on the available data: Prognosis symptom...
496     google  Based on the available data: Protocol malware ...
497     google  Based on the available data: Cold ever whose. ...
498      human  diagnosis cardiac clinical cardiac clinical pa...
499  anthropic  It is imperative to note that Clinical diagnos...

[500 rows x 2 columns]

## AI vs Human Scientific Text Dataset (AIGTxt)

In [18]:
df = pd.read_csv('../raw_data/AIGTxt.csv', delimiter=";")
df

,Human-Generated,ChatGPT-Generated,Mixed Text,Domain,Unnamed: 4
0,Photo-realistic image rendering using standard...,Achieving photo-realistic image rendering thro...,Achieving photo-realistic image rendering thro...,Computer Science and Artificial Intelligence,NaN
1,The Large Hadron Collider is exploring physics...,The Large Hadron Collider (LHC) serves as a fr...,The Large Hadron Collider (LHC) serves as a fr...,Computer Science and Artificial Intelligence,NaN
2,With the rapid development of mobile Internet ...,In the era of swift advancements in mobile Int...,In the era of swift advancements in mobile Int...,Computer Science and Artificial Intelligence,NaN
3,Most contour tracking methods can be grouped i...,Contour tracking methods can be broadly catego...,Contour tracking methods can be broadly catego...,Computer Science and Artificial Intelligence,NaN
4,Year 2010 is regarded as the breakthrough year...,The pivotal year 2010 marked a significant bre...,The pivotal year 2010 marked a significant bre...,Computer Science and Artificial Intelligence,NaN
...,...,...,...,...,...
3602,The increasing infrastructure instability is a...,Urban areas are increasingly experiencing infr...,Urban areas are increasingly experiencing infr...,Social Sciences and Humanities,NaN
3603,Even though it is commonly understood that mor...,While it is widely acknowledged that addressin...,While it is widely acknowledged that addressin...,Social Sciences and Humanities,NaN
3604,With the realisation that stakeholders across ...,Educational practitioners and academics have i...,With the realisation that stakeholders across ...,Social Sciences and Humanities,NaN
3605,"In this room, created by the non-governmental ...","Within this space, established by the non-gove...","Within this space, established by the non-gove...",Social Sciences and Humanities,NaN
3606,"Young onset dementias (YOD), i.e. dementias pr...","Young onset dementias (YOD), referring to deme...","Young onset dementias (YOD), referring to deme...",Social Sciences and Humanities,NaN

In [19]:
df_human = pd.DataFrame(df["Human-Generated"])
df_human.rename(columns={"Human-Generated":"text"}, inplace=True)
df_human["source"] = "human"
df_human

                                                   text source
0     Photo-realistic image rendering using standard...  human
1     The Large Hadron Collider is exploring physics...  human
2     With the rapid development of mobile Internet ...  human
3     Most contour tracking methods can be grouped i...  human
4     Year 2010 is regarded as the breakthrough year...  human
...                                                 ...    ...
3602  The increasing infrastructure instability is a...  human
3603  Even though it is commonly understood that mor...  human
3604  With the realisation that stakeholders across ...  human
3605  In this room, created by the non-governmental ...  human
3606  Young onset dementias (YOD), i.e. dementias pr...  human

[3607 rows x 2 columns]

In [20]:
df_ai = pd.DataFrame(df["ChatGPT-Generated"])
df_ai.rename(columns={"ChatGPT-Generated":"text"}, inplace=True)
df_ai["source"] = "openai"
df_ai

                                                   text  source
0     Achieving photo-realistic image rendering thro...  openai
1     The Large Hadron Collider (LHC) serves as a fr...  openai
2     In the era of swift advancements in mobile Int...  openai
3     Contour tracking methods can be broadly catego...  openai
4     The pivotal year 2010 marked a significant bre...  openai
...                                                 ...     ...
3602  Urban areas are increasingly experiencing infr...  openai
3603  While it is widely acknowledged that addressin...  openai
3604  Educational practitioners and academics have i...  openai
3605  Within this space, established by the non-gove...  openai
3606  Young onset dementias (YOD), referring to deme...  openai

[3607 rows x 2 columns]

In [21]:
df_4 = pd.concat([df_human, df_ai])
df_4.reset_index(drop=True, inplace=True)
df_4

                                                   text  source
0     Photo-realistic image rendering using standard...   human
1     The Large Hadron Collider is exploring physics...   human
2     With the rapid development of mobile Internet ...   human
3     Most contour tracking methods can be grouped i...   human
4     Year 2010 is regarded as the breakthrough year...   human
...                                                 ...     ...
7209  Urban areas are increasingly experiencing infr...  openai
7210  While it is widely acknowledged that addressin...  openai
7211  Educational practitioners and academics have i...  openai
7212  Within this space, established by the non-gove...  openai
7213  Young onset dementias (YOD), referring to deme...  openai

[7214 rows x 2 columns]

## Human vs. LLM Text Corpus

In [22]:
df = pd.read_csv('../raw_data/humanvsllm_data.csv')
df

,text,source,prompt_id,text_length,word_count
0,"Federal law supersedes state law, and cannabis...",Bloom-7B,0,967,157
1,Miles feels restless after working all day. He...,Bloom-7B,0,5068,778
2,So first of I am danish. That means that I fol...,Bloom-7B,0,1602,267
3,In this paper we present a novel rule-based ap...,Bloom-7B,0,5469,848
4,"Most social progressives, love democracy, and ...",Bloom-7B,0,2379,380
...,...,...,...,...,...
788917,"\nIn the vast expanse of time, where the echoe...",YI-34B,1293,5523,870
788918,"\nThe phenomenon of brain drain, particularly ...",YI-34B,1154,4540,677
788919,\nThe Influence of Climate Change on Marine Ec...,YI-34B,2783,3889,598
788920,\nTitle: The Case for Limiting Car Usage: Navi...,YI-34B,41,3560,533
788921,"\nIn the vast expanse of a globalized society,...",YI-34B,4318,4563,693

In [23]:
source_mapping = {
    "Human": "human",
    "GPT-3.5": "openai",
    "Text-Davinci-003": "openai",
    "Text-Davinci-002": "openai",
    "OPT-1.3B": "meta",
    "OPT-30B": "meta",
    "PaLM-2": "google",
    "LLaMA-30B": "meta",
    "LLaMA-65B": "meta",
    "LLaMA-13B": "meta",
    "LLaMA-7B": "meta",
    "Flan-T5-Base": "google",
    "Flan-T5-Large": "google",
    "Flan-T5-Small": "google",
    "OPT-2.7B": "meta",
    "Flan-T5-XXL": "google",
    "Flan-T5-XL": "google",
    "GPT-4": "openai",
    "OPT-6.7B": "meta",
    "OPT-125M": "meta",
    "OPT-350M": "meta",
    "OPT-13B": "meta",
    "GPT-J": "openai",
    "Claude-Instant-v1": "anthropic",
    "GPT-NeoX": "openai",
    "LLaMA-2-70B": "meta",
    "Claude-v1": "anthropic",
    "Gemini-Pro": "google",
    "LLaMA-2-7B": "meta"
}

In [24]:
df = df[df["source"].isin(source_mapping.keys())][["source", "text"]]
df

                   source                                               text
8812    Claude-Instant-v1   The rapid disappearance of forests around the...
8813    Claude-Instant-v1   The Healing Garden\n\nIt was a warm summer ev...
8814    Claude-Instant-v1  Drivers Should Avoid Cell Phone Use While Oper...
8815    Claude-Instant-v1  I agree with the principal's decision that all...
8816    Claude-Instant-v1  Dear Principal Johnson, \n\nI am writing to ex...
...                   ...                                                ...
778871   Text-Davinci-003  The first amendment has the "Free Exercise" cl...
778872   Text-Davinci-003  It means a plasma that is made of quarks and g...
778873   Text-Davinci-003  ISIS has been successful at recruiting middle ...
778874   Text-Davinci-003  A researcher from the Swiss research institute...
778875   Text-Davinci-003  It is not true that Islam is incompatible with...

[656397 rows x 2 columns]

In [25]:
df_5 = pd.DataFrame(df["text"])
df_5["source"] = df.apply(lambda row: source_mapping[row["source"]], axis=1)
df_5.reset_index(drop=True, inplace=True)
df_5

                                                     text     source
0        The rapid disappearance of forests around the...  anthropic
1        The Healing Garden\n\nIt was a warm summer ev...  anthropic
2       Drivers Should Avoid Cell Phone Use While Oper...  anthropic
3       I agree with the principal's decision that all...  anthropic
4       Dear Principal Johnson, \n\nI am writing to ex...  anthropic
...                                                   ...        ...
656392  The first amendment has the "Free Exercise" cl...     openai
656393  It means a plasma that is made of quarks and g...     openai
656394  ISIS has been successful at recruiting middle ...     openai
656395  A researcher from the Swiss research institute...     openai
656396  It is not true that Islam is incompatible with...     openai

[656397 rows x 2 columns]

## Final Dataset

In [26]:
df_final = pd.concat([df_1, df_2, df_3, df_4, df_5])
df_final.shape

(668664, 2)

In [27]:
df_final["basic_text"] = df_final["text"].str.upper()
df_final.head()

,source,text,basic_text
0,human,Chemistry is the scientific study of the prope...,CHEMISTRY IS THE SCIENTIFIC STUDY OF THE PROPE...
1,human,"Buddhism, also known as Buddha Dharma or Dharm...","BUDDHISM, ALSO KNOWN AS BUDDHA DHARMA OR DHARM..."
2,human,Color or colour is the visual perceptual prope...,COLOR OR COLOUR IS THE VISUAL PERCEPTUAL PROPE...
3,human,In the fields of molecular biology and genetic...,IN THE FIELDS OF MOLECULAR BIOLOGY AND GENETIC...
4,human,Photosynthesis is a process used by plants and...,PHOTOSYNTHESIS IS A PROCESS USED BY PLANTS AND...

In [28]:
df_final = df_final.drop_duplicates(subset=['basic_text'])
df_final.shape

(668596, 3)

In [29]:
df_final.source.value_counts(dropna=False)

source
human        353650
openai       125959
meta         122773
google        55814
anthropic     10400
Name: count, dtype: int64

In [ ]:
# df_final.to_csv('../custom_dataset_v1.csv')

In [ ]:
df_tmp = df_final[df_final["source"] == "anthropic"]
df_final_mini = df_final[df_final["source"] != "anthropic"].groupby("source").sample(n=50000, random_state=42)
df_final_mini = pd.concat([df_final_mini, df_tmp])
df_final_mini.source.value_counts(dropna=False)

source
google       50000
human        50000
meta         50000
openai       50000
anthropic    10400
Name: count, dtype: int64

In [ ]:
df_final_mini.to_csv('../custom_dataset_v1_mini.csv')